version: '2'
services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=32768"
      - "DB_HOST=prueba"
      - "DB_HOST=127.0.0.1"
      - "DB_DATABASE=docker"
      - "DB_USERNAME=docker"
      - "DB_PASSWORD=docker"
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8081:80
volumes:
  dbdata:
